<?php

namespace Desarrolla2\Bundle\PlanetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BlogBundle\Entity\Post;

/**
 * LinkPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkPostRepository extends EntityRepository
{
    public function getLink(Post $post)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            ' SELECT lp ' .
            ' FROM PlanetBundle:LinkPost lp ' .
            ' WHERE lp.post = :post'
        )->setParameter('post', $post)
            ->setMaxResults(1);

        $lp =  $query->getOneOrNullResult();
        if(!$lp){
            return;
        }
        return $lp->getLink();
    }
}
