<?php

namespace Desarrolla2\Bundle\PlanetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BlogBundle\Entity\Post;
use Desarrolla2\Bundle\BlogBundle\Entity\Link;
use DateTime;

/**
 * PostLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLinkRepository extends EntityRepository
{
    /**
     * @param Post $post
     * @return mixed
     */
    public function getLink(Post $post)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            ' SELECT lp ' .
            ' FROM PlanetBundle:PostLink lp ' .
            ' WHERE lp.post = :post'
        )
            ->setParameter('post', $post)
            ->setMaxResults(1);

        $lp = $query->getOneOrNullResult();
        if (!$lp) {
            return false;
        }

        return $lp->getLink();
    }

    /**
     * @param Link     $link
     * @param DateTime $from
     * @param DateTime $to
     * @return int
     */
    public function countFromTo(Link $link, DateTime $from, DateTime $to)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            ' SELECT COUNT(lp) FROM PlanetBundle:PostLink lp' .
            ' WHERE lp.link = :link ' .
            ' AND lp.createdAt > :from ' .
            ' AND lp.createdAt <= :to  '
        )
            ->setParameter('link', $link)
            ->setParameter('from', $from)
            ->setParameter('to', $to)
        ;

        return $query->getSingleScalarResult();
    }
}
