<?php

namespace Desarrolla2\Bundle\PlanetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostGuidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostGuidRepository extends EntityRepository
{
}
