<?php

namespace Desarrolla2\Bundle\PlanetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BlogBundle\Model\PostStatus;

/**
 * UnrelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnrelatedRepository extends EntityRepository
{

    public function getPost()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                ' SELECT p as post, COUNT(u) n FROM PlanetBundle:Unrelated u  ' .
                ' JOIN u.BlogBundle:Post p ' .
                ' WHERE p.status =  ' . PostStatus::PUBLISHED .
                ' GROUP BY p ' .
                ' HAVING  n > 0 ' .
                ' ORDER BY n DESC ' 
        );

        return $query->getResult();
    }

}
