<?php

namespace Desarrolla2\Bundle\PlanetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnrelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnrelatedRepository extends EntityRepository {

    public function getPost() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        ' SELECT COUNT(p) FROM BlogBundle:Post p ' .
                        ' JOIN p.tags t ' .
                        ' WHERE p.isPublished = 1 ' .
                        ' AND t = :t ' .
                        ' ORDER BY p.createdAt DESC '
                )
                ->setParameter('t', $t);

        return $query;
    }

}
